apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: hotel-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083

          env:
            - name: SPRING_APPLICATION_NAME
              value: hotel-service
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/hotel_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

          resources:
            requests:
              memory: "180Mi"
              cpu: "150m"
            limits:
              memory: "300Mi"
              cpu: "300m"
