apiVersion: v1
kind: Service
metadata:
  name: hotel-gateway
  labels:
    app: hotel-gateway
spec:
  selector:
    app: hotel-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
